# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- test

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: ServConnectionName
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show

- task: CmdLine@2
  displayName: 'ACR Login'
  inputs:
   script: docker login $(SKAFFOLD_DEFAULT_REPO) -u $(ACR_USER) -p $(ACR_PASSWORD)

# - task: ACRAKSAccess@0
#   inputs:
#     acrSubscriptionEndpoint: 'ServConnectionName'
#     aksSubscriptionEndpoint: 'ServConnectionName'
#     registerMode: 'RBAC'
#     acrResourceGroupName: 'diego-gomez'
#     containerRegistry: 'teamthreeAzureContRegist'
#     aksResourceGroupName: 'diego-gomez'
#     aksCluster: 'teamthree-k8s'
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'teamthree-k8s-dev'
    namespace: 'dev'
    command: 'get'
    arguments: 'namespaces'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'

# - task: CmdLine@2
#   displayName: 'Monitoring namespace conditional'
#   inputs:
#    script: |
#     kubectl create namespace monitoring --dry-run=client -o yaml



- task: HelmInstaller@0
  inputs:
    helmVersion: '2.5.0'
    installKubectl: true
- task: helm@1
  inputs:
    subCommand: 'repo'
    arguments: 'add prometheus-community https://prometheus-community.github.io/helm-charts'
    
- task: CmdLine@2
  displayName: 'Skaffold installation'
  inputs:
    script: |
      echo "$(KUBE_CONFIG)" | base64 -d > ~/.kube/config
      kubectl get namespaces
      curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
        chmod +x skaffold && \
        sudo mv skaffold /usr/local/bin

- task: CmdLine@2
  displayName: 'Skaffold version'
  inputs:
    script: 'skaffold version'

# - task: CmdLine@2
#   displayName: 'Skaffold deploy'
#   inputs:
#     script: skaffold run

# - task: CmdLine@2
#   displayName: 'Wait for pods'
#   inputs:
#     script: |
#       set -x
#         kubectl config set-context --current --namespace=$(NAMESPACE)
#         kubectl wait --for=condition=available --timeout=300s adservice
#         kubectl wait --for=condition=available --timeout=300s cartservice
#         kubectl wait --for=condition=available --timeout=300s checkoutservice
#         kubectl wait --for=condition=available --timeout=300s currencyservice
#         kubectl wait --for=condition=available --timeout=300s emailservice
#         kubectl wait --for=condition=available --timeout=300s frontend
#         kubectl wait --for=condition=available --timeout=300s frontend-external
#         kubectl wait --for=condition=available --timeout=300s paymentservice
#         kubectl wait --for=condition=available --timeout=300s productcatalogservice
#         kubectl wait --for=condition=available --timeout=300s recommendationservice
#         kubectl wait --for=condition=available --timeout=300s redis-cart
#         kubectl wait --for=condition=available --timeout=300s shippingservice

# - task: k6-load-test@0
#   inputs:
#     filename: 'test.js'