# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: ServConnectionName
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show

- task: CmdLine@2
  displayName: 'ACR Login'
  inputs:
   script: docker login $(SKAFFOLD_DEFAULT_REPO) -u $(ACR_USER) -p $(ACR_PASSWORD)

# - task: ACRAKSAccess@0
#   inputs:
#     acrSubscriptionEndpoint: 'ServConnectionName'
#     aksSubscriptionEndpoint: 'ServConnectionName'
#     registerMode: 'RBAC'
#     acrResourceGroupName: 'diego-gomez'
#     containerRegistry: 'teamthreeAzureContRegist'
#     aksResourceGroupName: 'diego-gomez'
#     aksCluster: 'teamthree-k8s'

- task: CmdLine@2
  displayName: 'Skaffold installation'
  inputs:
    script: |
      kubectl get ns
      curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
        chmod +x skaffold && \
        sudo mv skaffold /usr/local/bin

- task: CmdLine@2
  displayName: 'Skaffold version'
  inputs:
    script: 'skaffold version'

# - task: CmdLine@2
#   displayName: 'Download images from ACR'
#   inputs:
#     script: skaffold run --tail