# Skaffold version
apiVersion: skaffold/v1beta2
# The Skaffold configuration file has the kind Config
kind: Config
# The images to build
build:
#Artifacts that would be generated after building
  artifacts:
  # Name of the image to be uploaded to ACR
  - image: emailservice
  # Where the Dockerfile is located
    context: src/emailservice
  - image: productcatalogservice
    context: src/productcatalogservice
  - image: recommendationservice
    context: src/recommendationservice
  - image: shippingservice
    context: src/shippingservice
  - image: checkoutservice
    context: src/checkoutservice
  - image: paymentservice
    context: src/paymentservice
  - image: currencyservice
    context: src/currencyservice
  - image: cartservice
    context: src/cartservice/src
  - image: frontend
    context: src/frontend
  - image: loadgenerator
    context: src/loadgenerator
  - image: adservice
    context: src/adservice
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: false
# K8S configurated deployment
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml